# Generated by Django 4.0.2 on 2022-02-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Income_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_group', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField()),
                ('customer_id', models.CharField(max_length=255)),
                ('premiun', models.IntegerField()),
                ('bodily_injury_liablility', models.BooleanField(default=False)),
                ('personal_injury_protection', models.BooleanField(default=False)),
                ('property_damage_liablility', models.BooleanField(default=False)),
                ('collision', models.BooleanField(default=False)),
                ('comprehensive', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=8)),
                ('customer_marital_status', models.BooleanField(default=False)),
                ('customer_income_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer_income_group')),
                ('customer_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer_region')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fuel')),
                ('vehicle_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle_segment')),
            ],
        ),
    ]
